# Generated by Django 3.0.4 on 2020-05-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200511_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Poster',
            new_name='poster',
        ),
    ]
